import { tanstackRouter } from "@tanstack/router-plugin/vite";
import { vanillaExtractPlugin } from "@vanilla-extract/vite-plugin";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

// oxlint-disable-next-line import/no-default-export -- Vite loads its configuration from the default export.
export default defineConfig({
  plugins: [tanstackRouter({ target: "react", autoCodeSplitting: true, routeTreeFileHeader: ["// Generated by the TanStack Router plugin from src/routes. Never edit."] }), react(), vanillaExtractPlugin()],
  server: { proxy: { "/api": { target: "http://localhost:4310", ws: true } } },
  build: { outDir: "dist", emptyOutDir: true },
});
