/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/signIn/index'
import { Route as WWorkspaceIdRouteRouteImport } from './routes/w/$workspaceId/route'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w/$workspaceId/index'
import { Route as WWorkspaceIdInboxIndexRouteImport } from './routes/w/$workspaceId/inbox/index'
import { Route as WWorkspaceIdProjectsIndexRouteImport } from './routes/w/$workspaceId/projects/index'
import { Route as WWorkspaceIdRunsIndexRouteImport } from './routes/w/$workspaceId/runs/index'
import { Route as WWorkspaceIdSettingsIndexRouteImport } from './routes/w/$workspaceId/settings/index'
import { Route as WWorkspaceIdStandardsIndexRouteImport } from './routes/w/$workspaceId/standards/index'
import { Route as WWorkspaceIdPProjectIdIndexRouteImport } from './routes/w/$workspaceId/p/$projectId/index'
import { Route as WWorkspaceIdRunsRunIdIndexRouteImport } from './routes/w/$workspaceId/runs/$runId/index'
import { Route as WWorkspaceIdStandardsStandardIdIndexRouteImport } from './routes/w/$workspaceId/standards/$standardId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/signIn/',
  path: '/signIn/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdRouteRoute = WWorkspaceIdRouteRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdInboxIndexRoute = WWorkspaceIdInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdProjectsIndexRoute =
  WWorkspaceIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => WWorkspaceIdRouteRoute,
  } as any)
const WWorkspaceIdRunsIndexRoute = WWorkspaceIdRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdSettingsIndexRoute =
  WWorkspaceIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => WWorkspaceIdRouteRoute,
  } as any)
const WWorkspaceIdStandardsIndexRoute =
  WWorkspaceIdStandardsIndexRouteImport.update({
    id: '/standards/',
    path: '/standards/',
    getParentRoute: () => WWorkspaceIdRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdIndexRoute =
  WWorkspaceIdPProjectIdIndexRouteImport.update({
    id: '/p/$projectId/',
    path: '/p/$projectId/',
    getParentRoute: () => WWorkspaceIdRouteRoute,
  } as any)
const WWorkspaceIdRunsRunIdIndexRoute =
  WWorkspaceIdRunsRunIdIndexRouteImport.update({
    id: '/runs/$runId/',
    path: '/runs/$runId/',
    getParentRoute: () => WWorkspaceIdRouteRoute,
  } as any)
const WWorkspaceIdStandardsStandardIdIndexRoute =
  WWorkspaceIdStandardsStandardIdIndexRouteImport.update({
    id: '/standards/$standardId/',
    path: '/standards/$standardId/',
    getParentRoute: () => WWorkspaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteRouteWithChildren
  '/signIn/': typeof SignInIndexRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/inbox/': typeof WWorkspaceIdInboxIndexRoute
  '/w/$workspaceId/projects/': typeof WWorkspaceIdProjectsIndexRoute
  '/w/$workspaceId/runs/': typeof WWorkspaceIdRunsIndexRoute
  '/w/$workspaceId/settings/': typeof WWorkspaceIdSettingsIndexRoute
  '/w/$workspaceId/standards/': typeof WWorkspaceIdStandardsIndexRoute
  '/w/$workspaceId/p/$projectId/': typeof WWorkspaceIdPProjectIdIndexRoute
  '/w/$workspaceId/runs/$runId/': typeof WWorkspaceIdRunsRunIdIndexRoute
  '/w/$workspaceId/standards/$standardId/': typeof WWorkspaceIdStandardsStandardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof SignInIndexRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/inbox': typeof WWorkspaceIdInboxIndexRoute
  '/w/$workspaceId/projects': typeof WWorkspaceIdProjectsIndexRoute
  '/w/$workspaceId/runs': typeof WWorkspaceIdRunsIndexRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsIndexRoute
  '/w/$workspaceId/standards': typeof WWorkspaceIdStandardsIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdIndexRoute
  '/w/$workspaceId/runs/$runId': typeof WWorkspaceIdRunsRunIdIndexRoute
  '/w/$workspaceId/standards/$standardId': typeof WWorkspaceIdStandardsStandardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteRouteWithChildren
  '/signIn/': typeof SignInIndexRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/inbox/': typeof WWorkspaceIdInboxIndexRoute
  '/w/$workspaceId/projects/': typeof WWorkspaceIdProjectsIndexRoute
  '/w/$workspaceId/runs/': typeof WWorkspaceIdRunsIndexRoute
  '/w/$workspaceId/settings/': typeof WWorkspaceIdSettingsIndexRoute
  '/w/$workspaceId/standards/': typeof WWorkspaceIdStandardsIndexRoute
  '/w/$workspaceId/p/$projectId/': typeof WWorkspaceIdPProjectIdIndexRoute
  '/w/$workspaceId/runs/$runId/': typeof WWorkspaceIdRunsRunIdIndexRoute
  '/w/$workspaceId/standards/$standardId/': typeof WWorkspaceIdStandardsStandardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/$workspaceId'
    | '/signIn/'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/inbox/'
    | '/w/$workspaceId/projects/'
    | '/w/$workspaceId/runs/'
    | '/w/$workspaceId/settings/'
    | '/w/$workspaceId/standards/'
    | '/w/$workspaceId/p/$projectId/'
    | '/w/$workspaceId/runs/$runId/'
    | '/w/$workspaceId/standards/$standardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signIn'
    | '/w/$workspaceId'
    | '/w/$workspaceId/inbox'
    | '/w/$workspaceId/projects'
    | '/w/$workspaceId/runs'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/standards'
    | '/w/$workspaceId/p/$projectId'
    | '/w/$workspaceId/runs/$runId'
    | '/w/$workspaceId/standards/$standardId'
  id:
    | '__root__'
    | '/'
    | '/w/$workspaceId'
    | '/signIn/'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/inbox/'
    | '/w/$workspaceId/projects/'
    | '/w/$workspaceId/runs/'
    | '/w/$workspaceId/settings/'
    | '/w/$workspaceId/standards/'
    | '/w/$workspaceId/p/$projectId/'
    | '/w/$workspaceId/runs/$runId/'
    | '/w/$workspaceId/standards/$standardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WWorkspaceIdRouteRoute: typeof WWorkspaceIdRouteRouteWithChildren
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signIn/': {
      id: '/signIn/'
      path: '/signIn'
      fullPath: '/signIn/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId': {
      id: '/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof WWorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/inbox/': {
      id: '/w/$workspaceId/inbox/'
      path: '/inbox'
      fullPath: '/w/$workspaceId/inbox/'
      preLoaderRoute: typeof WWorkspaceIdInboxIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/projects/': {
      id: '/w/$workspaceId/projects/'
      path: '/projects'
      fullPath: '/w/$workspaceId/projects/'
      preLoaderRoute: typeof WWorkspaceIdProjectsIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/runs/': {
      id: '/w/$workspaceId/runs/'
      path: '/runs'
      fullPath: '/w/$workspaceId/runs/'
      preLoaderRoute: typeof WWorkspaceIdRunsIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/settings/': {
      id: '/w/$workspaceId/settings/'
      path: '/settings'
      fullPath: '/w/$workspaceId/settings/'
      preLoaderRoute: typeof WWorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/standards/': {
      id: '/w/$workspaceId/standards/'
      path: '/standards'
      fullPath: '/w/$workspaceId/standards/'
      preLoaderRoute: typeof WWorkspaceIdStandardsIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId/': {
      id: '/w/$workspaceId/p/$projectId/'
      path: '/p/$projectId'
      fullPath: '/w/$workspaceId/p/$projectId/'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/runs/$runId/': {
      id: '/w/$workspaceId/runs/$runId/'
      path: '/runs/$runId'
      fullPath: '/w/$workspaceId/runs/$runId/'
      preLoaderRoute: typeof WWorkspaceIdRunsRunIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/standards/$standardId/': {
      id: '/w/$workspaceId/standards/$standardId/'
      path: '/standards/$standardId'
      fullPath: '/w/$workspaceId/standards/$standardId/'
      preLoaderRoute: typeof WWorkspaceIdStandardsStandardIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
  }
}

interface WWorkspaceIdRouteRouteChildren {
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
  WWorkspaceIdInboxIndexRoute: typeof WWorkspaceIdInboxIndexRoute
  WWorkspaceIdProjectsIndexRoute: typeof WWorkspaceIdProjectsIndexRoute
  WWorkspaceIdRunsIndexRoute: typeof WWorkspaceIdRunsIndexRoute
  WWorkspaceIdSettingsIndexRoute: typeof WWorkspaceIdSettingsIndexRoute
  WWorkspaceIdStandardsIndexRoute: typeof WWorkspaceIdStandardsIndexRoute
  WWorkspaceIdPProjectIdIndexRoute: typeof WWorkspaceIdPProjectIdIndexRoute
  WWorkspaceIdRunsRunIdIndexRoute: typeof WWorkspaceIdRunsRunIdIndexRoute
  WWorkspaceIdStandardsStandardIdIndexRoute: typeof WWorkspaceIdStandardsStandardIdIndexRoute
}

const WWorkspaceIdRouteRouteChildren: WWorkspaceIdRouteRouteChildren = {
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
  WWorkspaceIdInboxIndexRoute: WWorkspaceIdInboxIndexRoute,
  WWorkspaceIdProjectsIndexRoute: WWorkspaceIdProjectsIndexRoute,
  WWorkspaceIdRunsIndexRoute: WWorkspaceIdRunsIndexRoute,
  WWorkspaceIdSettingsIndexRoute: WWorkspaceIdSettingsIndexRoute,
  WWorkspaceIdStandardsIndexRoute: WWorkspaceIdStandardsIndexRoute,
  WWorkspaceIdPProjectIdIndexRoute: WWorkspaceIdPProjectIdIndexRoute,
  WWorkspaceIdRunsRunIdIndexRoute: WWorkspaceIdRunsRunIdIndexRoute,
  WWorkspaceIdStandardsStandardIdIndexRoute:
    WWorkspaceIdStandardsStandardIdIndexRoute,
}

const WWorkspaceIdRouteRouteWithChildren =
  WWorkspaceIdRouteRoute._addFileChildren(WWorkspaceIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WWorkspaceIdRouteRoute: WWorkspaceIdRouteRouteWithChildren,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
